//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\kirot\source\repos\AnlrArbol\AnlrArbol\recipebook.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class recipebookLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, LINE_START=9, 
		GUION=10, REC_LBL=11, POR_LBL=12, TMP_LBL=13, TMC_LBL=14, CAL_LBL=15, 
		ING_LBL=16, ELA_LBL=17, LIST_ORDER_SEP=18, COM=19, SEP=20, TAB=21, WS=22, 
		NL=23, TEXT=24, WORD=25, NUMBER=26, FLOAT=27, INTEGER=28, CARRRET=29;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "LINE_START", 
		"GUION", "REC_LBL", "POR_LBL", "TMP_LBL", "TMC_LBL", "CAL_LBL", "ING_LBL", 
		"ELA_LBL", "LIST_ORDER_SEP", "COM", "SEP", "TAB", "WS", "NL", "TEXT", 
		"WORD", "NUMBER", "FLOAT", "INTEGER", "CARRRET"
	};


	public recipebookLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public recipebookLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'min'", "'minute'", "'sec'", "'second'", "'hr'", "'hour'", "'day'", 
		"'s'", null, "'-'", "'RECETA'", "'PORCIONES'", "'TIEMPO PREPARACION'", 
		"'TIEMPO COCCION'", "'CALORIAS'", "'INGREDIENTES'", "'ELABORACION'", "')'", 
		"','", "':'", "'\t'", null, "'\n'", null, null, null, null, null, "'\r'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, "LINE_START", "GUION", 
		"REC_LBL", "POR_LBL", "TMP_LBL", "TMC_LBL", "CAL_LBL", "ING_LBL", "ELA_LBL", 
		"LIST_ORDER_SEP", "COM", "SEP", "TAB", "WS", "NL", "TEXT", "WORD", "NUMBER", 
		"FLOAT", "INTEGER", "CARRRET"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "recipebook.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static recipebookLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1F', '\xF0', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x6', '\x17', 
		'\xC5', '\n', '\x17', '\r', '\x17', '\xE', '\x17', '\xC6', '\x3', '\x18', 
		'\x3', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', 
		'\a', '\x19', '\xCF', '\n', '\x19', '\f', '\x19', '\xE', '\x19', '\xD2', 
		'\v', '\x19', '\x3', '\x1A', '\x6', '\x1A', '\xD5', '\n', '\x1A', '\r', 
		'\x1A', '\xE', '\x1A', '\xD6', '\x3', '\x1B', '\x3', '\x1B', '\x5', '\x1B', 
		'\xDB', '\n', '\x1B', '\x3', '\x1C', '\x6', '\x1C', '\xDE', '\n', '\x1C', 
		'\r', '\x1C', '\xE', '\x1C', '\xDF', '\x3', '\x1C', '\x3', '\x1C', '\x6', 
		'\x1C', '\xE4', '\n', '\x1C', '\r', '\x1C', '\xE', '\x1C', '\xE5', '\x3', 
		'\x1D', '\x6', '\x1D', '\xE9', '\n', '\x1D', '\r', '\x1D', '\xE', '\x1D', 
		'\xEA', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x2', 
		'\x2', '\x1F', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', 
		'\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', 
		'\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', 
		'!', '\x12', '#', '\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', 
		'\x17', '-', '\x18', '/', '\x19', '\x31', '\x1A', '\x33', '\x1B', '\x35', 
		'\x1C', '\x37', '\x1D', '\x39', '\x1E', ';', '\x1F', '\x3', '\x2', '\x4', 
		'\x5', '\x2', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x3', '\x2', 
		'\x32', ';', '\x2', '\xF6', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', 
		'\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x2', '\x39', 
		'\x3', '\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', '\x3', 
		'=', '\x3', '\x2', '\x2', '\x2', '\x5', '\x41', '\x3', '\x2', '\x2', '\x2', 
		'\a', 'H', '\x3', '\x2', '\x2', '\x2', '\t', 'L', '\x3', '\x2', '\x2', 
		'\x2', '\v', 'S', '\x3', '\x2', '\x2', '\x2', '\r', 'V', '\x3', '\x2', 
		'\x2', '\x2', '\xF', '[', '\x3', '\x2', '\x2', '\x2', '\x11', '_', '\x3', 
		'\x2', '\x2', '\x2', '\x13', '\x61', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'\x64', '\x3', '\x2', '\x2', '\x2', '\x17', '\x66', '\x3', '\x2', '\x2', 
		'\x2', '\x19', 'm', '\x3', '\x2', '\x2', '\x2', '\x1B', 'w', '\x3', '\x2', 
		'\x2', '\x2', '\x1D', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x99', 
		'\x3', '\x2', '\x2', '\x2', '!', '\xA2', '\x3', '\x2', '\x2', '\x2', '#', 
		'\xAF', '\x3', '\x2', '\x2', '\x2', '%', '\xBB', '\x3', '\x2', '\x2', 
		'\x2', '\'', '\xBD', '\x3', '\x2', '\x2', '\x2', ')', '\xBF', '\x3', '\x2', 
		'\x2', '\x2', '+', '\xC1', '\x3', '\x2', '\x2', '\x2', '-', '\xC4', '\x3', 
		'\x2', '\x2', '\x2', '/', '\xC8', '\x3', '\x2', '\x2', '\x2', '\x31', 
		'\xCA', '\x3', '\x2', '\x2', '\x2', '\x33', '\xD4', '\x3', '\x2', '\x2', 
		'\x2', '\x35', '\xDA', '\x3', '\x2', '\x2', '\x2', '\x37', '\xDD', '\x3', 
		'\x2', '\x2', '\x2', '\x39', '\xE8', '\x3', '\x2', '\x2', '\x2', ';', 
		'\xEC', '\x3', '\x2', '\x2', '\x2', '=', '>', '\a', 'o', '\x2', '\x2', 
		'>', '?', '\a', 'k', '\x2', '\x2', '?', '@', '\a', 'p', '\x2', '\x2', 
		'@', '\x4', '\x3', '\x2', '\x2', '\x2', '\x41', '\x42', '\a', 'o', '\x2', 
		'\x2', '\x42', '\x43', '\a', 'k', '\x2', '\x2', '\x43', '\x44', '\a', 
		'p', '\x2', '\x2', '\x44', '\x45', '\a', 'w', '\x2', '\x2', '\x45', '\x46', 
		'\a', 'v', '\x2', '\x2', '\x46', 'G', '\a', 'g', '\x2', '\x2', 'G', '\x6', 
		'\x3', '\x2', '\x2', '\x2', 'H', 'I', '\a', 'u', '\x2', '\x2', 'I', 'J', 
		'\a', 'g', '\x2', '\x2', 'J', 'K', '\a', '\x65', '\x2', '\x2', 'K', '\b', 
		'\x3', '\x2', '\x2', '\x2', 'L', 'M', '\a', 'u', '\x2', '\x2', 'M', 'N', 
		'\a', 'g', '\x2', '\x2', 'N', 'O', '\a', '\x65', '\x2', '\x2', 'O', 'P', 
		'\a', 'q', '\x2', '\x2', 'P', 'Q', '\a', 'p', '\x2', '\x2', 'Q', 'R', 
		'\a', '\x66', '\x2', '\x2', 'R', '\n', '\x3', '\x2', '\x2', '\x2', 'S', 
		'T', '\a', 'j', '\x2', '\x2', 'T', 'U', '\a', 't', '\x2', '\x2', 'U', 
		'\f', '\x3', '\x2', '\x2', '\x2', 'V', 'W', '\a', 'j', '\x2', '\x2', 'W', 
		'X', '\a', 'q', '\x2', '\x2', 'X', 'Y', '\a', 'w', '\x2', '\x2', 'Y', 
		'Z', '\a', 't', '\x2', '\x2', 'Z', '\xE', '\x3', '\x2', '\x2', '\x2', 
		'[', '\\', '\a', '\x66', '\x2', '\x2', '\\', ']', '\a', '\x63', '\x2', 
		'\x2', ']', '^', '\a', '{', '\x2', '\x2', '^', '\x10', '\x3', '\x2', '\x2', 
		'\x2', '_', '`', '\a', 'u', '\x2', '\x2', '`', '\x12', '\x3', '\x2', '\x2', 
		'\x2', '\x61', '\x62', '\x5', '\x15', '\v', '\x2', '\x62', '\x63', '\x5', 
		'-', '\x17', '\x2', '\x63', '\x14', '\x3', '\x2', '\x2', '\x2', '\x64', 
		'\x65', '\a', '/', '\x2', '\x2', '\x65', '\x16', '\x3', '\x2', '\x2', 
		'\x2', '\x66', 'g', '\a', 'T', '\x2', '\x2', 'g', 'h', '\a', 'G', '\x2', 
		'\x2', 'h', 'i', '\a', '\x45', '\x2', '\x2', 'i', 'j', '\a', 'G', '\x2', 
		'\x2', 'j', 'k', '\a', 'V', '\x2', '\x2', 'k', 'l', '\a', '\x43', '\x2', 
		'\x2', 'l', '\x18', '\x3', '\x2', '\x2', '\x2', 'm', 'n', '\a', 'R', '\x2', 
		'\x2', 'n', 'o', '\a', 'Q', '\x2', '\x2', 'o', 'p', '\a', 'T', '\x2', 
		'\x2', 'p', 'q', '\a', '\x45', '\x2', '\x2', 'q', 'r', '\a', 'K', '\x2', 
		'\x2', 'r', 's', '\a', 'Q', '\x2', '\x2', 's', 't', '\a', 'P', '\x2', 
		'\x2', 't', 'u', '\a', 'G', '\x2', '\x2', 'u', 'v', '\a', 'U', '\x2', 
		'\x2', 'v', '\x1A', '\x3', '\x2', '\x2', '\x2', 'w', 'x', '\a', 'V', '\x2', 
		'\x2', 'x', 'y', '\a', 'K', '\x2', '\x2', 'y', 'z', '\a', 'G', '\x2', 
		'\x2', 'z', '{', '\a', 'O', '\x2', '\x2', '{', '|', '\a', 'R', '\x2', 
		'\x2', '|', '}', '\a', 'Q', '\x2', '\x2', '}', '~', '\a', '\"', '\x2', 
		'\x2', '~', '\x7F', '\a', 'R', '\x2', '\x2', '\x7F', '\x80', '\a', 'T', 
		'\x2', '\x2', '\x80', '\x81', '\a', 'G', '\x2', '\x2', '\x81', '\x82', 
		'\a', 'R', '\x2', '\x2', '\x82', '\x83', '\a', '\x43', '\x2', '\x2', '\x83', 
		'\x84', '\a', 'T', '\x2', '\x2', '\x84', '\x85', '\a', '\x43', '\x2', 
		'\x2', '\x85', '\x86', '\a', '\x45', '\x2', '\x2', '\x86', '\x87', '\a', 
		'K', '\x2', '\x2', '\x87', '\x88', '\a', 'Q', '\x2', '\x2', '\x88', '\x89', 
		'\a', 'P', '\x2', '\x2', '\x89', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x8A', 
		'\x8B', '\a', 'V', '\x2', '\x2', '\x8B', '\x8C', '\a', 'K', '\x2', '\x2', 
		'\x8C', '\x8D', '\a', 'G', '\x2', '\x2', '\x8D', '\x8E', '\a', 'O', '\x2', 
		'\x2', '\x8E', '\x8F', '\a', 'R', '\x2', '\x2', '\x8F', '\x90', '\a', 
		'Q', '\x2', '\x2', '\x90', '\x91', '\a', '\"', '\x2', '\x2', '\x91', '\x92', 
		'\a', '\x45', '\x2', '\x2', '\x92', '\x93', '\a', 'Q', '\x2', '\x2', '\x93', 
		'\x94', '\a', '\x45', '\x2', '\x2', '\x94', '\x95', '\a', '\x45', '\x2', 
		'\x2', '\x95', '\x96', '\a', 'K', '\x2', '\x2', '\x96', '\x97', '\a', 
		'Q', '\x2', '\x2', '\x97', '\x98', '\a', 'P', '\x2', '\x2', '\x98', '\x1E', 
		'\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', '\a', '\x45', '\x2', '\x2', 
		'\x9A', '\x9B', '\a', '\x43', '\x2', '\x2', '\x9B', '\x9C', '\a', 'N', 
		'\x2', '\x2', '\x9C', '\x9D', '\a', 'Q', '\x2', '\x2', '\x9D', '\x9E', 
		'\a', 'T', '\x2', '\x2', '\x9E', '\x9F', '\a', 'K', '\x2', '\x2', '\x9F', 
		'\xA0', '\a', '\x43', '\x2', '\x2', '\xA0', '\xA1', '\a', 'U', '\x2', 
		'\x2', '\xA1', ' ', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA3', '\a', 
		'K', '\x2', '\x2', '\xA3', '\xA4', '\a', 'P', '\x2', '\x2', '\xA4', '\xA5', 
		'\a', 'I', '\x2', '\x2', '\xA5', '\xA6', '\a', 'T', '\x2', '\x2', '\xA6', 
		'\xA7', '\a', 'G', '\x2', '\x2', '\xA7', '\xA8', '\a', '\x46', '\x2', 
		'\x2', '\xA8', '\xA9', '\a', 'K', '\x2', '\x2', '\xA9', '\xAA', '\a', 
		'G', '\x2', '\x2', '\xAA', '\xAB', '\a', 'P', '\x2', '\x2', '\xAB', '\xAC', 
		'\a', 'V', '\x2', '\x2', '\xAC', '\xAD', '\a', 'G', '\x2', '\x2', '\xAD', 
		'\xAE', '\a', 'U', '\x2', '\x2', '\xAE', '\"', '\x3', '\x2', '\x2', '\x2', 
		'\xAF', '\xB0', '\a', 'G', '\x2', '\x2', '\xB0', '\xB1', '\a', 'N', '\x2', 
		'\x2', '\xB1', '\xB2', '\a', '\x43', '\x2', '\x2', '\xB2', '\xB3', '\a', 
		'\x44', '\x2', '\x2', '\xB3', '\xB4', '\a', 'Q', '\x2', '\x2', '\xB4', 
		'\xB5', '\a', 'T', '\x2', '\x2', '\xB5', '\xB6', '\a', '\x43', '\x2', 
		'\x2', '\xB6', '\xB7', '\a', '\x45', '\x2', '\x2', '\xB7', '\xB8', '\a', 
		'K', '\x2', '\x2', '\xB8', '\xB9', '\a', 'Q', '\x2', '\x2', '\xB9', '\xBA', 
		'\a', 'P', '\x2', '\x2', '\xBA', '$', '\x3', '\x2', '\x2', '\x2', '\xBB', 
		'\xBC', '\a', '+', '\x2', '\x2', '\xBC', '&', '\x3', '\x2', '\x2', '\x2', 
		'\xBD', '\xBE', '\a', '.', '\x2', '\x2', '\xBE', '(', '\x3', '\x2', '\x2', 
		'\x2', '\xBF', '\xC0', '\a', '<', '\x2', '\x2', '\xC0', '*', '\x3', '\x2', 
		'\x2', '\x2', '\xC1', '\xC2', '\a', '\v', '\x2', '\x2', '\xC2', ',', '\x3', 
		'\x2', '\x2', '\x2', '\xC3', '\xC5', '\a', '\"', '\x2', '\x2', '\xC4', 
		'\xC3', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC6', '\x3', '\x2', '\x2', 
		'\x2', '\xC6', '\xC4', '\x3', '\x2', '\x2', '\x2', '\xC6', '\xC7', '\x3', 
		'\x2', '\x2', '\x2', '\xC7', '.', '\x3', '\x2', '\x2', '\x2', '\xC8', 
		'\xC9', '\a', '\f', '\x2', '\x2', '\xC9', '\x30', '\x3', '\x2', '\x2', 
		'\x2', '\xCA', '\xD0', '\x5', '\x33', '\x1A', '\x2', '\xCB', '\xCC', '\x5', 
		'-', '\x17', '\x2', '\xCC', '\xCD', '\x5', '\x33', '\x1A', '\x2', '\xCD', 
		'\xCF', '\x3', '\x2', '\x2', '\x2', '\xCE', '\xCB', '\x3', '\x2', '\x2', 
		'\x2', '\xCF', '\xD2', '\x3', '\x2', '\x2', '\x2', '\xD0', '\xCE', '\x3', 
		'\x2', '\x2', '\x2', '\xD0', '\xD1', '\x3', '\x2', '\x2', '\x2', '\xD1', 
		'\x32', '\x3', '\x2', '\x2', '\x2', '\xD2', '\xD0', '\x3', '\x2', '\x2', 
		'\x2', '\xD3', '\xD5', '\t', '\x2', '\x2', '\x2', '\xD4', '\xD3', '\x3', 
		'\x2', '\x2', '\x2', '\xD5', '\xD6', '\x3', '\x2', '\x2', '\x2', '\xD6', 
		'\xD4', '\x3', '\x2', '\x2', '\x2', '\xD6', '\xD7', '\x3', '\x2', '\x2', 
		'\x2', '\xD7', '\x34', '\x3', '\x2', '\x2', '\x2', '\xD8', '\xDB', '\x5', 
		'\x39', '\x1D', '\x2', '\xD9', '\xDB', '\x5', '\x37', '\x1C', '\x2', '\xDA', 
		'\xD8', '\x3', '\x2', '\x2', '\x2', '\xDA', '\xD9', '\x3', '\x2', '\x2', 
		'\x2', '\xDB', '\x36', '\x3', '\x2', '\x2', '\x2', '\xDC', '\xDE', '\t', 
		'\x3', '\x2', '\x2', '\xDD', '\xDC', '\x3', '\x2', '\x2', '\x2', '\xDE', 
		'\xDF', '\x3', '\x2', '\x2', '\x2', '\xDF', '\xDD', '\x3', '\x2', '\x2', 
		'\x2', '\xDF', '\xE0', '\x3', '\x2', '\x2', '\x2', '\xE0', '\xE1', '\x3', 
		'\x2', '\x2', '\x2', '\xE1', '\xE3', '\a', '\x30', '\x2', '\x2', '\xE2', 
		'\xE4', '\t', '\x3', '\x2', '\x2', '\xE3', '\xE2', '\x3', '\x2', '\x2', 
		'\x2', '\xE4', '\xE5', '\x3', '\x2', '\x2', '\x2', '\xE5', '\xE3', '\x3', 
		'\x2', '\x2', '\x2', '\xE5', '\xE6', '\x3', '\x2', '\x2', '\x2', '\xE6', 
		'\x38', '\x3', '\x2', '\x2', '\x2', '\xE7', '\xE9', '\t', '\x3', '\x2', 
		'\x2', '\xE8', '\xE7', '\x3', '\x2', '\x2', '\x2', '\xE9', '\xEA', '\x3', 
		'\x2', '\x2', '\x2', '\xEA', '\xE8', '\x3', '\x2', '\x2', '\x2', '\xEA', 
		'\xEB', '\x3', '\x2', '\x2', '\x2', '\xEB', ':', '\x3', '\x2', '\x2', 
		'\x2', '\xEC', '\xED', '\a', '\xF', '\x2', '\x2', '\xED', '\xEE', '\x3', 
		'\x2', '\x2', '\x2', '\xEE', '\xEF', '\b', '\x1E', '\x2', '\x2', '\xEF', 
		'<', '\x3', '\x2', '\x2', '\x2', '\n', '\x2', '\xC6', '\xD0', '\xD6', 
		'\xDA', '\xDF', '\xE5', '\xEA', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
