//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\kirot\source\repos\AnlrArbol\AnlrArbol\recipebook.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class recipebookParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		LINE_START=1, GUION=2, REC_LBL=3, POR_LBL=4, TMP_LBL=5, TMC_LBL=6, CAL_LBL=7, 
		ING_LBL=8, ELA_LBL=9, TIME_UNIT=10, MEASURE_UNIT=11, WORD=12, LIST_ORDER_SEP=13, 
		COM=14, SEP=15, TAB=16, WS=17, NL=18, NUMBER=19, FLOAT=20, INTEGER=21, 
		CARRRET=22;
	public const int
		RULE_recipebook = 0, RULE_book = 1, RULE_entry = 2, RULE_recipe_tag = 3, 
		RULE_recipe_name = 4, RULE_portions_tag = 5, RULE_portion_unit = 6, RULE_prep_time_tag = 7, 
		RULE_cooking_time_tag = 8, RULE_calories_tag = 9, RULE_calories_content = 10, 
		RULE_calorie_unit = 11, RULE_ingredients_tag = 12, RULE_ingredient_list = 13, 
		RULE_ingredient_list_item = 14, RULE_ingredient = 15, RULE_measure = 16, 
		RULE_ingredient_name = 17, RULE_elaboration_tag = 18, RULE_elaboration_list = 19, 
		RULE_elaboration_list_item = 20, RULE_list_order = 21, RULE_order = 22, 
		RULE_instruction = 23, RULE_time = 24, RULE_time_unit = 25, RULE_amount = 26, 
		RULE_text = 27;
	public static readonly string[] ruleNames = {
		"recipebook", "book", "entry", "recipe_tag", "recipe_name", "portions_tag", 
		"portion_unit", "prep_time_tag", "cooking_time_tag", "calories_tag", "calories_content", 
		"calorie_unit", "ingredients_tag", "ingredient_list", "ingredient_list_item", 
		"ingredient", "measure", "ingredient_name", "elaboration_tag", "elaboration_list", 
		"elaboration_list_item", "list_order", "order", "instruction", "time", 
		"time_unit", "amount", "text"
	};

	private static readonly string[] _LiteralNames = {
		null, null, "'-'", "'RECETA'", "'PORCIONES'", "'TIEMPO PREPARACION'", 
		"'TIEMPO COCCION'", "'CALORIAS'", "'INGREDIENTES'", "'ELABORACION'", null, 
		null, null, "')'", "','", "':'", "'\t'", null, "'\n'", null, null, null, 
		"'\r'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "LINE_START", "GUION", "REC_LBL", "POR_LBL", "TMP_LBL", "TMC_LBL", 
		"CAL_LBL", "ING_LBL", "ELA_LBL", "TIME_UNIT", "MEASURE_UNIT", "WORD", 
		"LIST_ORDER_SEP", "COM", "SEP", "TAB", "WS", "NL", "NUMBER", "FLOAT", 
		"INTEGER", "CARRRET"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "recipebook.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static recipebookParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public recipebookParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public recipebookParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class RecipebookContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public BookContext book() {
			return GetRuleContext<BookContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(recipebookParser.Eof, 0); }
		public RecipebookContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_recipebook; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRecipebook(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RecipebookContext recipebook() {
		RecipebookContext _localctx = new RecipebookContext(Context, State);
		EnterRule(_localctx, 0, RULE_recipebook);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 56;
			book();
			State = 57;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BookContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public EntryContext[] entry() {
			return GetRuleContexts<EntryContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public EntryContext entry(int i) {
			return GetRuleContext<EntryContext>(i);
		}
		public BookContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_book; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBook(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BookContext book() {
		BookContext _localctx = new BookContext(Context, State);
		EnterRule(_localctx, 2, RULE_book);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 60;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 59;
				entry();
				}
				}
				State = 62;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==LINE_START );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EntryContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Recipe_tagContext recipe_tag() {
			return GetRuleContext<Recipe_tagContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Portions_tagContext portions_tag() {
			return GetRuleContext<Portions_tagContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Calories_tagContext calories_tag() {
			return GetRuleContext<Calories_tagContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Ingredients_tagContext ingredients_tag() {
			return GetRuleContext<Ingredients_tagContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Elaboration_tagContext elaboration_tag() {
			return GetRuleContext<Elaboration_tagContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Prep_time_tagContext prep_time_tag() {
			return GetRuleContext<Prep_time_tagContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Cooking_time_tagContext cooking_time_tag() {
			return GetRuleContext<Cooking_time_tagContext>(0);
		}
		public EntryContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_entry; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEntry(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EntryContext entry() {
		EntryContext _localctx = new EntryContext(Context, State);
		EnterRule(_localctx, 4, RULE_entry);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 64;
			recipe_tag();
			State = 65;
			portions_tag();
			State = 67;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				{
				State = 66;
				prep_time_tag();
				}
				break;
			}
			State = 70;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				{
				State = 69;
				cooking_time_tag();
				}
				break;
			}
			State = 72;
			calories_tag();
			State = 73;
			ingredients_tag();
			State = 74;
			elaboration_tag();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Recipe_tagContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LINE_START() { return GetToken(recipebookParser.LINE_START, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REC_LBL() { return GetToken(recipebookParser.REC_LBL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEP() { return GetToken(recipebookParser.SEP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WS() { return GetToken(recipebookParser.WS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Recipe_nameContext recipe_name() {
			return GetRuleContext<Recipe_nameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NL() { return GetToken(recipebookParser.NL, 0); }
		public Recipe_tagContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_recipe_tag; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRecipe_tag(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Recipe_tagContext recipe_tag() {
		Recipe_tagContext _localctx = new Recipe_tagContext(Context, State);
		EnterRule(_localctx, 6, RULE_recipe_tag);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 76;
			Match(LINE_START);
			State = 77;
			Match(REC_LBL);
			State = 78;
			Match(SEP);
			State = 79;
			Match(WS);
			State = 80;
			recipe_name();
			State = 81;
			Match(NL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Recipe_nameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TextContext text() {
			return GetRuleContext<TextContext>(0);
		}
		public Recipe_nameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_recipe_name; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRecipe_name(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Recipe_nameContext recipe_name() {
		Recipe_nameContext _localctx = new Recipe_nameContext(Context, State);
		EnterRule(_localctx, 8, RULE_recipe_name);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 83;
			text();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Portions_tagContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LINE_START() { return GetToken(recipebookParser.LINE_START, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode POR_LBL() { return GetToken(recipebookParser.POR_LBL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEP() { return GetToken(recipebookParser.SEP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] WS() { return GetTokens(recipebookParser.WS); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WS(int i) {
			return GetToken(recipebookParser.WS, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AmountContext amount() {
			return GetRuleContext<AmountContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Portion_unitContext portion_unit() {
			return GetRuleContext<Portion_unitContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NL() { return GetToken(recipebookParser.NL, 0); }
		public Portions_tagContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_portions_tag; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPortions_tag(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Portions_tagContext portions_tag() {
		Portions_tagContext _localctx = new Portions_tagContext(Context, State);
		EnterRule(_localctx, 10, RULE_portions_tag);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 85;
			Match(LINE_START);
			State = 86;
			Match(POR_LBL);
			State = 87;
			Match(SEP);
			State = 88;
			Match(WS);
			State = 89;
			amount();
			State = 90;
			Match(WS);
			State = 91;
			portion_unit();
			State = 92;
			Match(NL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Portion_unitContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TextContext text() {
			return GetRuleContext<TextContext>(0);
		}
		public Portion_unitContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_portion_unit; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPortion_unit(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Portion_unitContext portion_unit() {
		Portion_unitContext _localctx = new Portion_unitContext(Context, State);
		EnterRule(_localctx, 12, RULE_portion_unit);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 94;
			text();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Prep_time_tagContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LINE_START() { return GetToken(recipebookParser.LINE_START, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TMP_LBL() { return GetToken(recipebookParser.TMP_LBL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEP() { return GetToken(recipebookParser.SEP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WS() { return GetToken(recipebookParser.WS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TimeContext time() {
			return GetRuleContext<TimeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NL() { return GetToken(recipebookParser.NL, 0); }
		public Prep_time_tagContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_prep_time_tag; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPrep_time_tag(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Prep_time_tagContext prep_time_tag() {
		Prep_time_tagContext _localctx = new Prep_time_tagContext(Context, State);
		EnterRule(_localctx, 14, RULE_prep_time_tag);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 96;
			Match(LINE_START);
			State = 97;
			Match(TMP_LBL);
			State = 98;
			Match(SEP);
			State = 99;
			Match(WS);
			State = 100;
			time();
			State = 101;
			Match(NL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cooking_time_tagContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LINE_START() { return GetToken(recipebookParser.LINE_START, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TMC_LBL() { return GetToken(recipebookParser.TMC_LBL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEP() { return GetToken(recipebookParser.SEP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WS() { return GetToken(recipebookParser.WS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TimeContext time() {
			return GetRuleContext<TimeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NL() { return GetToken(recipebookParser.NL, 0); }
		public Cooking_time_tagContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cooking_time_tag; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCooking_time_tag(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Cooking_time_tagContext cooking_time_tag() {
		Cooking_time_tagContext _localctx = new Cooking_time_tagContext(Context, State);
		EnterRule(_localctx, 16, RULE_cooking_time_tag);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 103;
			Match(LINE_START);
			State = 104;
			Match(TMC_LBL);
			State = 105;
			Match(SEP);
			State = 106;
			Match(WS);
			State = 107;
			time();
			State = 108;
			Match(NL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Calories_tagContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LINE_START() { return GetToken(recipebookParser.LINE_START, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CAL_LBL() { return GetToken(recipebookParser.CAL_LBL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEP() { return GetToken(recipebookParser.SEP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WS() { return GetToken(recipebookParser.WS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Calories_contentContext calories_content() {
			return GetRuleContext<Calories_contentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NL() { return GetToken(recipebookParser.NL, 0); }
		public Calories_tagContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_calories_tag; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCalories_tag(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Calories_tagContext calories_tag() {
		Calories_tagContext _localctx = new Calories_tagContext(Context, State);
		EnterRule(_localctx, 18, RULE_calories_tag);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 110;
			Match(LINE_START);
			State = 111;
			Match(CAL_LBL);
			State = 112;
			Match(SEP);
			State = 113;
			Match(WS);
			State = 114;
			calories_content();
			State = 115;
			Match(NL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Calories_contentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AmountContext amount() {
			return GetRuleContext<AmountContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WS() { return GetToken(recipebookParser.WS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Calorie_unitContext calorie_unit() {
			return GetRuleContext<Calorie_unitContext>(0);
		}
		public Calories_contentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_calories_content; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCalories_content(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Calories_contentContext calories_content() {
		Calories_contentContext _localctx = new Calories_contentContext(Context, State);
		EnterRule(_localctx, 20, RULE_calories_content);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 117;
			amount();
			State = 118;
			Match(WS);
			State = 119;
			calorie_unit();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Calorie_unitContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TextContext text() {
			return GetRuleContext<TextContext>(0);
		}
		public Calorie_unitContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_calorie_unit; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCalorie_unit(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Calorie_unitContext calorie_unit() {
		Calorie_unitContext _localctx = new Calorie_unitContext(Context, State);
		EnterRule(_localctx, 22, RULE_calorie_unit);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 121;
			text();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Ingredients_tagContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LINE_START() { return GetToken(recipebookParser.LINE_START, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ING_LBL() { return GetToken(recipebookParser.ING_LBL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEP() { return GetToken(recipebookParser.SEP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NL() { return GetTokens(recipebookParser.NL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NL(int i) {
			return GetToken(recipebookParser.NL, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Ingredient_listContext ingredient_list() {
			return GetRuleContext<Ingredient_listContext>(0);
		}
		public Ingredients_tagContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ingredients_tag; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIngredients_tag(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Ingredients_tagContext ingredients_tag() {
		Ingredients_tagContext _localctx = new Ingredients_tagContext(Context, State);
		EnterRule(_localctx, 24, RULE_ingredients_tag);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 123;
			Match(LINE_START);
			State = 124;
			Match(ING_LBL);
			State = 125;
			Match(SEP);
			State = 126;
			Match(NL);
			State = 127;
			ingredient_list();
			State = 128;
			Match(NL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Ingredient_listContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Ingredient_list_itemContext[] ingredient_list_item() {
			return GetRuleContexts<Ingredient_list_itemContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Ingredient_list_itemContext ingredient_list_item(int i) {
			return GetRuleContext<Ingredient_list_itemContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COM() { return GetTokens(recipebookParser.COM); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COM(int i) {
			return GetToken(recipebookParser.COM, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NL() { return GetTokens(recipebookParser.NL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NL(int i) {
			return GetToken(recipebookParser.NL, i);
		}
		public Ingredient_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ingredient_list; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIngredient_list(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Ingredient_listContext ingredient_list() {
		Ingredient_listContext _localctx = new Ingredient_listContext(Context, State);
		EnterRule(_localctx, 26, RULE_ingredient_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 130;
			ingredient_list_item();
			State = 136;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COM) {
				{
				{
				State = 131;
				Match(COM);
				State = 132;
				Match(NL);
				State = 133;
				ingredient_list_item();
				}
				}
				State = 138;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Ingredient_list_itemContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TAB() { return GetToken(recipebookParser.TAB, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public AmountContext amount() {
			return GetRuleContext<AmountContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WS() { return GetToken(recipebookParser.WS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public IngredientContext ingredient() {
			return GetRuleContext<IngredientContext>(0);
		}
		public Ingredient_list_itemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ingredient_list_item; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIngredient_list_item(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Ingredient_list_itemContext ingredient_list_item() {
		Ingredient_list_itemContext _localctx = new Ingredient_list_itemContext(Context, State);
		EnterRule(_localctx, 28, RULE_ingredient_list_item);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 139;
			Match(TAB);
			State = 140;
			amount();
			State = 141;
			Match(WS);
			State = 142;
			ingredient();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IngredientContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Ingredient_nameContext ingredient_name() {
			return GetRuleContext<Ingredient_nameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MeasureContext measure() {
			return GetRuleContext<MeasureContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WS() { return GetToken(recipebookParser.WS, 0); }
		public IngredientContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ingredient; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIngredient(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IngredientContext ingredient() {
		IngredientContext _localctx = new IngredientContext(Context, State);
		EnterRule(_localctx, 30, RULE_ingredient);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 147;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==MEASURE_UNIT) {
				{
				State = 144;
				measure();
				State = 145;
				Match(WS);
				}
			}

			State = 149;
			ingredient_name();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MeasureContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MEASURE_UNIT() { return GetToken(recipebookParser.MEASURE_UNIT, 0); }
		public MeasureContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_measure; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMeasure(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MeasureContext measure() {
		MeasureContext _localctx = new MeasureContext(Context, State);
		EnterRule(_localctx, 32, RULE_measure);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 151;
			Match(MEASURE_UNIT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Ingredient_nameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TextContext text() {
			return GetRuleContext<TextContext>(0);
		}
		public Ingredient_nameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ingredient_name; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIngredient_name(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Ingredient_nameContext ingredient_name() {
		Ingredient_nameContext _localctx = new Ingredient_nameContext(Context, State);
		EnterRule(_localctx, 34, RULE_ingredient_name);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 153;
			text();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Elaboration_tagContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LINE_START() { return GetToken(recipebookParser.LINE_START, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELA_LBL() { return GetToken(recipebookParser.ELA_LBL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEP() { return GetToken(recipebookParser.SEP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NL() { return GetTokens(recipebookParser.NL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NL(int i) {
			return GetToken(recipebookParser.NL, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Elaboration_listContext elaboration_list() {
			return GetRuleContext<Elaboration_listContext>(0);
		}
		public Elaboration_tagContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elaboration_tag; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitElaboration_tag(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Elaboration_tagContext elaboration_tag() {
		Elaboration_tagContext _localctx = new Elaboration_tagContext(Context, State);
		EnterRule(_localctx, 36, RULE_elaboration_tag);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 155;
			Match(LINE_START);
			State = 156;
			Match(ELA_LBL);
			State = 157;
			Match(SEP);
			State = 158;
			Match(NL);
			State = 159;
			elaboration_list();
			State = 161;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==NL) {
				{
				State = 160;
				Match(NL);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Elaboration_listContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Elaboration_list_itemContext[] elaboration_list_item() {
			return GetRuleContexts<Elaboration_list_itemContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Elaboration_list_itemContext elaboration_list_item(int i) {
			return GetRuleContext<Elaboration_list_itemContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NL() { return GetTokens(recipebookParser.NL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NL(int i) {
			return GetToken(recipebookParser.NL, i);
		}
		public Elaboration_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elaboration_list; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitElaboration_list(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Elaboration_listContext elaboration_list() {
		Elaboration_listContext _localctx = new Elaboration_listContext(Context, State);
		EnterRule(_localctx, 38, RULE_elaboration_list);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 163;
			elaboration_list_item();
			State = 168;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,6,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 164;
					Match(NL);
					State = 165;
					elaboration_list_item();
					}
					} 
				}
				State = 170;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,6,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Elaboration_list_itemContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TAB() { return GetToken(recipebookParser.TAB, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public List_orderContext list_order() {
			return GetRuleContext<List_orderContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WS() { return GetToken(recipebookParser.WS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public InstructionContext instruction() {
			return GetRuleContext<InstructionContext>(0);
		}
		public Elaboration_list_itemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elaboration_list_item; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitElaboration_list_item(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Elaboration_list_itemContext elaboration_list_item() {
		Elaboration_list_itemContext _localctx = new Elaboration_list_itemContext(Context, State);
		EnterRule(_localctx, 40, RULE_elaboration_list_item);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 171;
			Match(TAB);
			State = 172;
			list_order();
			State = 173;
			Match(WS);
			State = 174;
			instruction();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class List_orderContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public OrderContext order() {
			return GetRuleContext<OrderContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LIST_ORDER_SEP() { return GetToken(recipebookParser.LIST_ORDER_SEP, 0); }
		public List_orderContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_list_order; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitList_order(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public List_orderContext list_order() {
		List_orderContext _localctx = new List_orderContext(Context, State);
		EnterRule(_localctx, 42, RULE_list_order);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 176;
			order();
			State = 177;
			Match(LIST_ORDER_SEP);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OrderContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(recipebookParser.NUMBER, 0); }
		public OrderContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_order; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOrder(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OrderContext order() {
		OrderContext _localctx = new OrderContext(Context, State);
		EnterRule(_localctx, 44, RULE_order);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 179;
			Match(NUMBER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InstructionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TextContext text() {
			return GetRuleContext<TextContext>(0);
		}
		public InstructionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instruction; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInstruction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public InstructionContext instruction() {
		InstructionContext _localctx = new InstructionContext(Context, State);
		EnterRule(_localctx, 46, RULE_instruction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 181;
			text();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TimeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AmountContext amount() {
			return GetRuleContext<AmountContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WS() { return GetToken(recipebookParser.WS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Time_unitContext time_unit() {
			return GetRuleContext<Time_unitContext>(0);
		}
		public TimeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_time; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTime(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TimeContext time() {
		TimeContext _localctx = new TimeContext(Context, State);
		EnterRule(_localctx, 48, RULE_time);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 183;
			amount();
			State = 184;
			Match(WS);
			State = 185;
			time_unit();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Time_unitContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TIME_UNIT() { return GetToken(recipebookParser.TIME_UNIT, 0); }
		public Time_unitContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_time_unit; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTime_unit(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Time_unitContext time_unit() {
		Time_unitContext _localctx = new Time_unitContext(Context, State);
		EnterRule(_localctx, 50, RULE_time_unit);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 187;
			Match(TIME_UNIT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AmountContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(recipebookParser.NUMBER, 0); }
		public AmountContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_amount; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAmount(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AmountContext amount() {
		AmountContext _localctx = new AmountContext(Context, State);
		EnterRule(_localctx, 52, RULE_amount);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 189;
			Match(NUMBER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TextContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] WORD() { return GetTokens(recipebookParser.WORD); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WORD(int i) {
			return GetToken(recipebookParser.WORD, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] WS() { return GetTokens(recipebookParser.WS); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WS(int i) {
			return GetToken(recipebookParser.WS, i);
		}
		public TextContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_text; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IrecipebookVisitor<TResult> typedVisitor = visitor as IrecipebookVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitText(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TextContext text() {
		TextContext _localctx = new TextContext(Context, State);
		EnterRule(_localctx, 54, RULE_text);
		int _la;
		try {
			State = 200;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 191;
				Match(WORD);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 192;
				Match(WORD);
				State = 197;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==WS) {
					{
					{
					State = 193;
					Match(WS);
					State = 194;
					Match(WORD);
					}
					}
					State = 199;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x18', '\xCD', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x6', 
		'\x3', '?', '\n', '\x3', '\r', '\x3', '\xE', '\x3', '@', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x5', '\x4', '\x46', '\n', '\x4', '\x3', 
		'\x4', '\x5', '\x4', 'I', '\n', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', 
		'\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\a', '\xF', '\x89', '\n', '\xF', '\f', '\xF', '\xE', '\xF', 
		'\x8C', '\v', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x5', 
		'\x11', '\x96', '\n', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x5', '\x14', 
		'\xA4', '\n', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\a', 
		'\x15', '\xA9', '\n', '\x15', '\f', '\x15', '\xE', '\x15', '\xAC', '\v', 
		'\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', 
		'\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', 
		'\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\a', 
		'\x1D', '\xC6', '\n', '\x1D', '\f', '\x1D', '\xE', '\x1D', '\xC9', '\v', 
		'\x1D', '\x5', '\x1D', '\xCB', '\n', '\x1D', '\x3', '\x1D', '\x2', '\x2', 
		'\x1E', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', 
		'\x14', '\x16', '\x18', '\x1A', '\x1C', '\x1E', ' ', '\"', '$', '&', '(', 
		'*', ',', '.', '\x30', '\x32', '\x34', '\x36', '\x38', '\x2', '\x2', '\x2', 
		'\xB9', '\x2', ':', '\x3', '\x2', '\x2', '\x2', '\x4', '>', '\x3', '\x2', 
		'\x2', '\x2', '\x6', '\x42', '\x3', '\x2', '\x2', '\x2', '\b', 'N', '\x3', 
		'\x2', '\x2', '\x2', '\n', 'U', '\x3', '\x2', '\x2', '\x2', '\f', 'W', 
		'\x3', '\x2', '\x2', '\x2', '\xE', '`', '\x3', '\x2', '\x2', '\x2', '\x10', 
		'\x62', '\x3', '\x2', '\x2', '\x2', '\x12', 'i', '\x3', '\x2', '\x2', 
		'\x2', '\x14', 'p', '\x3', '\x2', '\x2', '\x2', '\x16', 'w', '\x3', '\x2', 
		'\x2', '\x2', '\x18', '{', '\x3', '\x2', '\x2', '\x2', '\x1A', '}', '\x3', 
		'\x2', '\x2', '\x2', '\x1C', '\x84', '\x3', '\x2', '\x2', '\x2', '\x1E', 
		'\x8D', '\x3', '\x2', '\x2', '\x2', ' ', '\x95', '\x3', '\x2', '\x2', 
		'\x2', '\"', '\x99', '\x3', '\x2', '\x2', '\x2', '$', '\x9B', '\x3', '\x2', 
		'\x2', '\x2', '&', '\x9D', '\x3', '\x2', '\x2', '\x2', '(', '\xA5', '\x3', 
		'\x2', '\x2', '\x2', '*', '\xAD', '\x3', '\x2', '\x2', '\x2', ',', '\xB2', 
		'\x3', '\x2', '\x2', '\x2', '.', '\xB5', '\x3', '\x2', '\x2', '\x2', '\x30', 
		'\xB7', '\x3', '\x2', '\x2', '\x2', '\x32', '\xB9', '\x3', '\x2', '\x2', 
		'\x2', '\x34', '\xBD', '\x3', '\x2', '\x2', '\x2', '\x36', '\xBF', '\x3', 
		'\x2', '\x2', '\x2', '\x38', '\xCA', '\x3', '\x2', '\x2', '\x2', ':', 
		';', '\x5', '\x4', '\x3', '\x2', ';', '<', '\a', '\x2', '\x2', '\x3', 
		'<', '\x3', '\x3', '\x2', '\x2', '\x2', '=', '?', '\x5', '\x6', '\x4', 
		'\x2', '>', '=', '\x3', '\x2', '\x2', '\x2', '?', '@', '\x3', '\x2', '\x2', 
		'\x2', '@', '>', '\x3', '\x2', '\x2', '\x2', '@', '\x41', '\x3', '\x2', 
		'\x2', '\x2', '\x41', '\x5', '\x3', '\x2', '\x2', '\x2', '\x42', '\x43', 
		'\x5', '\b', '\x5', '\x2', '\x43', '\x45', '\x5', '\f', '\a', '\x2', '\x44', 
		'\x46', '\x5', '\x10', '\t', '\x2', '\x45', '\x44', '\x3', '\x2', '\x2', 
		'\x2', '\x45', '\x46', '\x3', '\x2', '\x2', '\x2', '\x46', 'H', '\x3', 
		'\x2', '\x2', '\x2', 'G', 'I', '\x5', '\x12', '\n', '\x2', 'H', 'G', '\x3', 
		'\x2', '\x2', '\x2', 'H', 'I', '\x3', '\x2', '\x2', '\x2', 'I', 'J', '\x3', 
		'\x2', '\x2', '\x2', 'J', 'K', '\x5', '\x14', '\v', '\x2', 'K', 'L', '\x5', 
		'\x1A', '\xE', '\x2', 'L', 'M', '\x5', '&', '\x14', '\x2', 'M', '\a', 
		'\x3', '\x2', '\x2', '\x2', 'N', 'O', '\a', '\x3', '\x2', '\x2', 'O', 
		'P', '\a', '\x5', '\x2', '\x2', 'P', 'Q', '\a', '\x11', '\x2', '\x2', 
		'Q', 'R', '\a', '\x13', '\x2', '\x2', 'R', 'S', '\x5', '\n', '\x6', '\x2', 
		'S', 'T', '\a', '\x14', '\x2', '\x2', 'T', '\t', '\x3', '\x2', '\x2', 
		'\x2', 'U', 'V', '\x5', '\x38', '\x1D', '\x2', 'V', '\v', '\x3', '\x2', 
		'\x2', '\x2', 'W', 'X', '\a', '\x3', '\x2', '\x2', 'X', 'Y', '\a', '\x6', 
		'\x2', '\x2', 'Y', 'Z', '\a', '\x11', '\x2', '\x2', 'Z', '[', '\a', '\x13', 
		'\x2', '\x2', '[', '\\', '\x5', '\x36', '\x1C', '\x2', '\\', ']', '\a', 
		'\x13', '\x2', '\x2', ']', '^', '\x5', '\xE', '\b', '\x2', '^', '_', '\a', 
		'\x14', '\x2', '\x2', '_', '\r', '\x3', '\x2', '\x2', '\x2', '`', '\x61', 
		'\x5', '\x38', '\x1D', '\x2', '\x61', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x62', '\x63', '\a', '\x3', '\x2', '\x2', '\x63', '\x64', '\a', '\a', 
		'\x2', '\x2', '\x64', '\x65', '\a', '\x11', '\x2', '\x2', '\x65', '\x66', 
		'\a', '\x13', '\x2', '\x2', '\x66', 'g', '\x5', '\x32', '\x1A', '\x2', 
		'g', 'h', '\a', '\x14', '\x2', '\x2', 'h', '\x11', '\x3', '\x2', '\x2', 
		'\x2', 'i', 'j', '\a', '\x3', '\x2', '\x2', 'j', 'k', '\a', '\b', '\x2', 
		'\x2', 'k', 'l', '\a', '\x11', '\x2', '\x2', 'l', 'm', '\a', '\x13', '\x2', 
		'\x2', 'm', 'n', '\x5', '\x32', '\x1A', '\x2', 'n', 'o', '\a', '\x14', 
		'\x2', '\x2', 'o', '\x13', '\x3', '\x2', '\x2', '\x2', 'p', 'q', '\a', 
		'\x3', '\x2', '\x2', 'q', 'r', '\a', '\t', '\x2', '\x2', 'r', 's', '\a', 
		'\x11', '\x2', '\x2', 's', 't', '\a', '\x13', '\x2', '\x2', 't', 'u', 
		'\x5', '\x16', '\f', '\x2', 'u', 'v', '\a', '\x14', '\x2', '\x2', 'v', 
		'\x15', '\x3', '\x2', '\x2', '\x2', 'w', 'x', '\x5', '\x36', '\x1C', '\x2', 
		'x', 'y', '\a', '\x13', '\x2', '\x2', 'y', 'z', '\x5', '\x18', '\r', '\x2', 
		'z', '\x17', '\x3', '\x2', '\x2', '\x2', '{', '|', '\x5', '\x38', '\x1D', 
		'\x2', '|', '\x19', '\x3', '\x2', '\x2', '\x2', '}', '~', '\a', '\x3', 
		'\x2', '\x2', '~', '\x7F', '\a', '\n', '\x2', '\x2', '\x7F', '\x80', '\a', 
		'\x11', '\x2', '\x2', '\x80', '\x81', '\a', '\x14', '\x2', '\x2', '\x81', 
		'\x82', '\x5', '\x1C', '\xF', '\x2', '\x82', '\x83', '\a', '\x14', '\x2', 
		'\x2', '\x83', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x84', '\x8A', '\x5', 
		'\x1E', '\x10', '\x2', '\x85', '\x86', '\a', '\x10', '\x2', '\x2', '\x86', 
		'\x87', '\a', '\x14', '\x2', '\x2', '\x87', '\x89', '\x5', '\x1E', '\x10', 
		'\x2', '\x88', '\x85', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8C', '\x3', 
		'\x2', '\x2', '\x2', '\x8A', '\x88', '\x3', '\x2', '\x2', '\x2', '\x8A', 
		'\x8B', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x1D', '\x3', '\x2', '\x2', 
		'\x2', '\x8C', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8E', '\a', 
		'\x12', '\x2', '\x2', '\x8E', '\x8F', '\x5', '\x36', '\x1C', '\x2', '\x8F', 
		'\x90', '\a', '\x13', '\x2', '\x2', '\x90', '\x91', '\x5', ' ', '\x11', 
		'\x2', '\x91', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x92', '\x93', '\x5', 
		'\"', '\x12', '\x2', '\x93', '\x94', '\a', '\x13', '\x2', '\x2', '\x94', 
		'\x96', '\x3', '\x2', '\x2', '\x2', '\x95', '\x92', '\x3', '\x2', '\x2', 
		'\x2', '\x95', '\x96', '\x3', '\x2', '\x2', '\x2', '\x96', '\x97', '\x3', 
		'\x2', '\x2', '\x2', '\x97', '\x98', '\x5', '$', '\x13', '\x2', '\x98', 
		'!', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', '\a', '\r', '\x2', '\x2', 
		'\x9A', '#', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9C', '\x5', '\x38', 
		'\x1D', '\x2', '\x9C', '%', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9E', 
		'\a', '\x3', '\x2', '\x2', '\x9E', '\x9F', '\a', '\v', '\x2', '\x2', '\x9F', 
		'\xA0', '\a', '\x11', '\x2', '\x2', '\xA0', '\xA1', '\a', '\x14', '\x2', 
		'\x2', '\xA1', '\xA3', '\x5', '(', '\x15', '\x2', '\xA2', '\xA4', '\a', 
		'\x14', '\x2', '\x2', '\xA3', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA3', 
		'\xA4', '\x3', '\x2', '\x2', '\x2', '\xA4', '\'', '\x3', '\x2', '\x2', 
		'\x2', '\xA5', '\xAA', '\x5', '*', '\x16', '\x2', '\xA6', '\xA7', '\a', 
		'\x14', '\x2', '\x2', '\xA7', '\xA9', '\x5', '*', '\x16', '\x2', '\xA8', 
		'\xA6', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xAC', '\x3', '\x2', '\x2', 
		'\x2', '\xAA', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xAB', '\x3', 
		'\x2', '\x2', '\x2', '\xAB', ')', '\x3', '\x2', '\x2', '\x2', '\xAC', 
		'\xAA', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xAE', '\a', '\x12', '\x2', 
		'\x2', '\xAE', '\xAF', '\x5', ',', '\x17', '\x2', '\xAF', '\xB0', '\a', 
		'\x13', '\x2', '\x2', '\xB0', '\xB1', '\x5', '\x30', '\x19', '\x2', '\xB1', 
		'+', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB3', '\x5', '.', '\x18', '\x2', 
		'\xB3', '\xB4', '\a', '\xF', '\x2', '\x2', '\xB4', '-', '\x3', '\x2', 
		'\x2', '\x2', '\xB5', '\xB6', '\a', '\x15', '\x2', '\x2', '\xB6', '/', 
		'\x3', '\x2', '\x2', '\x2', '\xB7', '\xB8', '\x5', '\x38', '\x1D', '\x2', 
		'\xB8', '\x31', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xBA', '\x5', '\x36', 
		'\x1C', '\x2', '\xBA', '\xBB', '\a', '\x13', '\x2', '\x2', '\xBB', '\xBC', 
		'\x5', '\x34', '\x1B', '\x2', '\xBC', '\x33', '\x3', '\x2', '\x2', '\x2', 
		'\xBD', '\xBE', '\a', '\f', '\x2', '\x2', '\xBE', '\x35', '\x3', '\x2', 
		'\x2', '\x2', '\xBF', '\xC0', '\a', '\x15', '\x2', '\x2', '\xC0', '\x37', 
		'\x3', '\x2', '\x2', '\x2', '\xC1', '\xCB', '\a', '\xE', '\x2', '\x2', 
		'\xC2', '\xC7', '\a', '\xE', '\x2', '\x2', '\xC3', '\xC4', '\a', '\x13', 
		'\x2', '\x2', '\xC4', '\xC6', '\a', '\xE', '\x2', '\x2', '\xC5', '\xC3', 
		'\x3', '\x2', '\x2', '\x2', '\xC6', '\xC9', '\x3', '\x2', '\x2', '\x2', 
		'\xC7', '\xC5', '\x3', '\x2', '\x2', '\x2', '\xC7', '\xC8', '\x3', '\x2', 
		'\x2', '\x2', '\xC8', '\xCB', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xC7', 
		'\x3', '\x2', '\x2', '\x2', '\xCA', '\xC1', '\x3', '\x2', '\x2', '\x2', 
		'\xCA', '\xC2', '\x3', '\x2', '\x2', '\x2', '\xCB', '\x39', '\x3', '\x2', 
		'\x2', '\x2', '\v', '@', '\x45', 'H', '\x8A', '\x95', '\xA3', '\xAA', 
		'\xC7', '\xCA',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
